name: guitar-technique-classification
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10.*            # 建议固定主次版本，示例
  - numpy
  - scipy
  - pandas
  - scikit-learn
  - matplotlib
  - jupyter
  - librosa=0.11.*           # 你现在用的是 0.11.0
  - pysoundfile              # ← 这里用 pysoundfile（conda 包名）
  - ipykernel
  - pip
  - pip:
      - gradio               # 仍然走 pip

