name: guitar-technique-classification
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.13
  - numpy=2.2.*
  - scipy=1.16.*
  - scikit-learn=1.7.*
  - matplotlib=3.10.*
  - soundfile
  - jupyter
  - ipykernel
  - pip
  - pip:
      - librosa==0.11.*
      - soxr
