name: guitar-technique-classification
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - numpy
  - scipy
  - pandas
  - scikit-learn
  - matplotlib
  - jupyter
  - librosa=0.10.0
  - soundfile
  - pip
  - ipykernel
  - pip:
      - gradio
